USE [master]
GO

/****** Object:  Database [E-metro]    Script Date: 5/26/2023 10:22:46 AM ******/
CREATE DATABASE [E-metro]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'E-metro', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\E-metro.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'E-metro_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\E-metro_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [E-metro].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [E-metro] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [E-metro] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [E-metro] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [E-metro] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [E-metro] SET ARITHABORT OFF 
GO

ALTER DATABASE [E-metro] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [E-metro] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [E-metro] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [E-metro] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [E-metro] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [E-metro] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [E-metro] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [E-metro] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [E-metro] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [E-metro] SET  DISABLE_BROKER 
GO

ALTER DATABASE [E-metro] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [E-metro] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [E-metro] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [E-metro] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [E-metro] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [E-metro] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [E-metro] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [E-metro] SET RECOVERY FULL 
GO

ALTER DATABASE [E-metro] SET  MULTI_USER 
GO

ALTER DATABASE [E-metro] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [E-metro] SET DB_CHAINING OFF 
GO

ALTER DATABASE [E-metro] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [E-metro] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [E-metro] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [E-metro] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO

ALTER DATABASE [E-metro] SET QUERY_STORE = OFF
GO

ALTER DATABASE [E-metro] SET  READ_WRITE 
GO


